# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 232ed25026dca49fc62b765579f5700b42e871f4eb70958f3ac5e47a4411d8d42c47c556c58f32ac505a25d20e96a414ef969bca98e43abc5900220a7b79fa81

test:
  secret_key_base: 1471dcea5c2e34c17c93be0127e7f676abc586cfd49e41cfa0e13bee3756a7ad3354c8b2b16aad8daf5ddceaf90928bd91828e9a07659a160a9401bbbcc76db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
